/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type AbCampaignData struct {

	// 
	ABCampaignType float64 `json:"ABCampaignType,omitempty"`

	// 
	ABWinnerSelectionType float64 `json:"ABWinnerSelectionType,omitempty"`

	// 
	DeliveredOnA string `json:"DeliveredOnA,omitempty"`

	// 
	DeliveredOnB string `json:"DeliveredOnB,omitempty"`

	// 
	HTMLContentB string `json:"HTMLContentB,omitempty"`

	// 
	HoursToTest float64 `json:"HoursToTest,omitempty"`

	// 
	ID float64 `json:"ID,omitempty"`

	// 
	ListPercentage float64 `json:"ListPercentage,omitempty"`

	// 
	PlainContentB string `json:"PlainContentB,omitempty"`

	// 
	SenderB string `json:"SenderB,omitempty"`

	// 
	SubjectB string `json:"SubjectB,omitempty"`

	// 
	WebLocationB string `json:"WebLocationB,omitempty"`
}
