/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type ActivityByLocationResponse struct {

	// 
	Code float64 `json:"Code,omitempty"`

	Context Context110 `json:"Context,omitempty"`

	// 
	Error_ string `json:"Error,omitempty"`
}
