/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type AddingSubscribersRequest struct {

	// The email address of the member.
	Email string `json:"Email"`

	// The name of the member.
	Name string `json:"Name,omitempty"`

	// A list of name-value pairs that match the member's custom fields defined in the mailing list.  For example, if you have two custom fields named Age and Country, you should specify values for them as following example.
	CustomFields interface{} `json:"CustomFields,omitempty"`
}
