/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type AddingCriteriaToSegmentsRequest struct {

	// The field of the criterion to filter the mailing list by. This must be one of the following values.
	Field string `json:"Field"`

	// A search term to filter the specified field by.
	Value string `json:"Value"`

	// An operator that defines the way to compare a criterion field with its value. This must be one of the following values. If not specified, `Is` will be assumed.
	Comparer string `json:"Comparer,omitempty"`

	// Provides an additional filter option to be combined with the following fields.
	DateFrom string `json:"DateFrom,omitempty"`

	// Provides an additional filter option to be combined with the following fields.
	DateTo string `json:"DateTo,omitempty"`
}
