/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Analytic struct {

	// 
	Context string `json:"Context,omitempty"`

	// 
	ContextDescription string `json:"ContextDescription,omitempty"`

	// 
	ContextName string `json:"ContextName,omitempty"`

	// 
	TotalCount float64 `json:"TotalCount,omitempty"`

	// 
	UniqueCount float64 `json:"UniqueCount,omitempty"`
}
