/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Campaign struct {

	// 
	ABCampaignType float64 `json:"ABCampaignType,omitempty"`

	// 
	ABHoursToTest float64 `json:"ABHoursToTest,omitempty"`

	// 
	ABWinner float64 `json:"ABWinner,omitempty"`

	// 
	ABWinnerSelectionType float64 `json:"ABWinnerSelectionType,omitempty"`

	// 
	ConfirmationTo string `json:"ConfirmationTo,omitempty"`

	// 
	CreatedOn string `json:"CreatedOn,omitempty"`

	// 
	DeliveredOn string `json:"DeliveredOn,omitempty"`

	// 
	ID string `json:"ID,omitempty"`

	// 
	IsTransactional bool `json:"IsTransactional,omitempty"`

	// 
	MailingLists []MailingList68 `json:"MailingLists,omitempty"`

	// 
	Name string `json:"Name,omitempty"`

	// 
	RecipientsCount float64 `json:"RecipientsCount,omitempty"`

	// 
	ScheduledFor string `json:"ScheduledFor,omitempty"`

	// 
	ScheduledForTimezone string `json:"ScheduledForTimezone,omitempty"`

	// 
	SiteName string `json:"SiteName,omitempty"`

	// 
	Status float64 `json:"Status,omitempty"`

	// 
	Subject string `json:"Subject,omitempty"`

	// 
	TotalBounces float64 `json:"TotalBounces,omitempty"`

	// 
	TotalComplaints float64 `json:"TotalComplaints,omitempty"`

	// 
	TotalForwards float64 `json:"TotalForwards,omitempty"`

	// 
	TotalLinkClicks float64 `json:"TotalLinkClicks,omitempty"`

	// 
	TotalOpens float64 `json:"TotalOpens,omitempty"`

	// 
	TotalSent float64 `json:"TotalSent,omitempty"`

	// 
	TotalUnsubscribes float64 `json:"TotalUnsubscribes,omitempty"`

	// 
	UniqueForwards float64 `json:"UniqueForwards,omitempty"`

	// 
	UniqueLinkClicks float64 `json:"UniqueLinkClicks,omitempty"`

	// 
	UniqueOpens float64 `json:"UniqueOpens,omitempty"`
}
