/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context64 struct {

	// 
	EmailsIgnored float64 `json:"EmailsIgnored,omitempty"`

	// 
	EmailsProcessed float64 `json:"EmailsProcessed,omitempty"`
}
