/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context110 struct {

	// 
	Analytics []Analytic `json:"Analytics,omitempty"`

	Paging Paging `json:"Paging,omitempty"`
}
