/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context132 struct {

	A A `json:"A,omitempty"`

	B B `json:"B,omitempty"`

	// 
	CampaignID string `json:"CampaignID,omitempty"`
}
