/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context89 struct {

	// 
	CreatedOn string `json:"CreatedOn,omitempty"`

	// 
	DkimPublic string `json:"DkimPublic,omitempty"`

	// 
	DkimVerified bool `json:"DkimVerified,omitempty"`

	// 
	Email string `json:"Email,omitempty"`

	// 
	ID string `json:"ID,omitempty"`

	// 
	IsEnabled bool `json:"IsEnabled,omitempty"`

	// 
	Name string `json:"Name,omitempty"`

	// 
	SpfVerified bool `json:"SpfVerified,omitempty"`
}
