/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context148 struct {

	Paging Paging `json:"Paging,omitempty"`

	// 
	Subscribers []Subscribers150 `json:"Subscribers,omitempty"`
}
