/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Context72 struct {

	// 
	Campaigns []Campaign `json:"Campaigns,omitempty"`

	Paging Paging76 `json:"Paging,omitempty"`
}
