/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Criterion struct {

	// 
	Comparer float64 `json:"Comparer,omitempty"`

	// 
	CustomFieldID string `json:"CustomFieldID,omitempty"`

	// 
	DateFrom string `json:"DateFrom,omitempty"`

	// 
	DateTo string `json:"DateTo,omitempty"`

	// 
	Field float64 `json:"Field,omitempty"`

	// 
	ID float64 `json:"ID,omitempty"`

	// 
	Properties string `json:"Properties,omitempty"`

	// 
	SegmentID float64 `json:"SegmentID,omitempty"`

	// 
	Subscriteria string `json:"Subscriteria,omitempty"`

	// 
	Value string `json:"Value,omitempty"`
}
