/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type CustomFieldsDefinition struct {

	// 
	Context string `json:"Context,omitempty"`

	// 
	ID string `json:"ID,omitempty"`

	// 
	IsRequired bool `json:"IsRequired,omitempty"`

	// 
	Name string `json:"Name,omitempty"`

	// 
	Type_ float64 `json:"Type,omitempty"`
}
