/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type CustomField struct {

	// 
	CustomFieldID string `json:"CustomFieldID,omitempty"`

	// 
	Name string `json:"Name,omitempty"`

	// 
	Value string `json:"Value,omitempty"`
}
