/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type ImportOperation19 struct {

	// 
	CompletedOn string `json:"CompletedOn,omitempty"`

	// 
	CreatedOn string `json:"CreatedOn,omitempty"`

	// 
	DataHash string `json:"DataHash,omitempty"`

	// 
	EmailNotify string `json:"EmailNotify,omitempty"`

	// 
	ID float64 `json:"ID,omitempty"`

	// 
	Mappings string `json:"Mappings,omitempty"`

	// 
	Message string `json:"Message,omitempty"`

	// 
	SkipNewMembers bool `json:"SkipNewMembers,omitempty"`

	// 
	StartedOn string `json:"StartedOn,omitempty"`

	// 
	Success bool `json:"Success,omitempty"`

	// 
	TotalDuplicate float64 `json:"TotalDuplicate,omitempty"`

	// 
	TotalIgnored float64 `json:"TotalIgnored,omitempty"`

	// 
	TotalInserted float64 `json:"TotalInserted,omitempty"`

	// 
	TotalInvalid float64 `json:"TotalInvalid,omitempty"`

	// 
	TotalMembers float64 `json:"TotalMembers,omitempty"`

	// 
	TotalUnsubscribed float64 `json:"TotalUnsubscribed,omitempty"`

	// 
	TotalUpdated float64 `json:"TotalUpdated,omitempty"`
}
