/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type MailingList68 struct {

	// 
	Campaign string `json:"Campaign,omitempty"`

	MailingList MailingList69 `json:"MailingList,omitempty"`

	// 
	Segment string `json:"Segment,omitempty"`
}
