/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type MailingLists struct {

	// A Mailing list id
	MailingListId string `json:"MailingListId"`

	// Possible values : (whatever, random, fuck)
	SegmentId float64 `json:"SegmentId,omitempty"`
}
