/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type RemovingMultipleSubscribersRequest struct {

	// A list of email addresses to be removed, separated with a comma (,).
	Emails string `json:"Emails"`
}
