/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type SendingACampaignResponse struct {

	// 
	Code int32 `json:"Code"`

	// 
	Error_ string `json:"Error"`

	// 
	Context string `json:"Context"`
}
