/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type Subscribers150 struct {

	// 
	CreatedOn string `json:"CreatedOn,omitempty"`

	// 
	CustomFields []CustomField `json:"CustomFields,omitempty"`

	// 
	Email string `json:"Email,omitempty"`

	// 
	ID string `json:"ID,omitempty"`

	// 
	Name string `json:"Name,omitempty"`

	// 
	RemovedOn string `json:"RemovedOn,omitempty"`

	// 
	SubscribeMethod float64 `json:"SubscribeMethod,omitempty"`

	// 
	SubscribeType float64 `json:"SubscribeType,omitempty"`

	// 
	UnsubscribedFromID string `json:"UnsubscribedFromID,omitempty"`

	// 
	UnsubscribedOn string `json:"UnsubscribedOn,omitempty"`

	// 
	UpdatedOn string `json:"UpdatedOn,omitempty"`
}
