/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type TestingACampaignRequest struct {

	// A list of email addresses to send the preview to (maximum 5 recipients).
	TestEmails interface{} `json:"TestEmails"`
}
