/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type UnsubscribingSubscribersFromMailingListRequest struct {

	// The email address of the member.
	Email string `json:"Email"`
}
