/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type UpdatingAMailingListRequest struct {

	// The name of the new mailing list.
	Name string `json:"Name"`

	// The URL of the page that will be displayed at the end of the subscription process.
	ConfirmationPage string `json:"ConfirmationPage,omitempty"`

	// The URL of the page that users will be redirected after unsubscribing from your mailing list.
	RedirectAfterUnsubscribePage string `json:"RedirectAfterUnsubscribePage,omitempty"`
}
