/* 
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package Moosend.Wrappers.GOWrapper

type UpdatingADraftCampaignRequest struct {

	// The name of the campaign.
	Name string `json:"Name,omitempty"`

	// The subject line of the new campaign.
	Subject string `json:"Subject,omitempty"`

	// The sender email of the campaign.
	SenderEmail string `json:"SenderEmail,omitempty"`

	// The email address to which recipients replies will arrive. It must be one of your sender accounts. If not specified, the sender's email will be assumed.
	ReplyToEmail string `json:"ReplyToEmail,omitempty"`

	// A flag that defines if a campaign is an AB campaign.
	IsAB string `json:"IsAB,omitempty"`

	// The email address to which a confirmation message will be,  sent when the campaign has been successfully sent.
	ConfirmationToEmail string `json:"ConfirmationToEmail,omitempty"`

	// A url to retrieve the html content for the campaign. We'll automatically move all CSS inline.
	WebLocation string `json:"WebLocation,omitempty"`

	// A list of mailing lists in your account to which the campaign will be sent to.
	MailingLists []MailingLists `json:"MailingLists,omitempty"`

	// The ID of a segment in the specified mailing list to filter the recipients with. If not specified, the campaign will be sent to all active subscribers of the mailing list.
	SegmentID string `json:"SegmentID,omitempty"`

	// If you want to send an AB split campaign you should specify this parameter to one of the following values.  * `Subject` * `Sender` * `Content`
	ABCampaignType string `json:"ABCampaignType,omitempty"`

	// Tracks traffic from your campaign to your site. Note: You need to have Google Analytics configured on your site to use this feature.
	TrackInGoogleAnalytics string `json:"TrackInGoogleAnalytics,omitempty"`

	// Moosend wraps your own links with its own to enable link click tracking. Check this box if you don't wish to track link click traffic through Moosend.
	DontTrackLinkClicks string `json:"DontTrackLinkClicks,omitempty"`

	// If you wish to send an AB split campaign with two different versions of the subject line , you must specify the second subject using this parameter. If specified in any other campaign type, it will be ignored.
	SubjectB string `json:"SubjectB,omitempty"`

	// If you wish to send an AB split campaign with two different versions of the html content, you must specify where the second html content will be retrieved from using this parameter. If specified in any other campaign type, it will be ignored.
	WebLocationB string `json:"WebLocationB,omitempty"`

	// If you wish to send an AB split campaign with two different versions of the sender , you must specify the second sender email address using this parameter. This must be one of your sender signatures defined in your account. If specified in any other campaign type, it will be ignored.
	SenderEmailB string `json:"SenderEmailB,omitempty"`

	// If you choose to send an AB campaign type, you must set this parameter to specify how long the test will run, before determining which will be the winning version to be sent to the rest of the recipients. This should be an integer value between 1 and 24. If specified in a regular campaign, it will be ignored.
	HoursToTest string `json:"HoursToTest,omitempty"`

	// If you choose to send an AB campaign type, you must set this parameter to specify a portion of the target recipients that will receive the test versions. For example, if you specify 10, then 10% of your recipients will receive the A version and another 10% will receive the B version. The specified value should be an integer between 5 and 40. If specified in a regular campaign, it will be ignored. (optional, string)
	ListPercentage string `json:"ListPercentage,omitempty"`

	// If you choose to send an AB campaign type, you may set this parameter to one of the following values to specify the method to determine the winning version for the test.   If not set, OpenRate will be assumed. If specified in a regular campaign, it will be ignored. * `OpenRate` * `TotalUniqueClicks`
	ABWinnerSelectionType string `json:"ABWinnerSelectionType,omitempty"`
}
